# Generated by Django 4.2.4 on 2023-09-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0003_alter_entrada_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('mensaje', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.URLField(max_length=1000),
        ),
    ]
