# Generated by Django 4.2.4 on 2023-09-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0005_rename_contenido_entrada_cuerpo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
