# Generated by Django 4.2.4 on 2023-09-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0007_alter_entrada_slug_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='active',
            new_name='activo',
        ),
    ]
