# Generated by Django 4.2.4 on 2023-09-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0008_rename_active_comentario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
