# Generated by Django 4.2.4 on 2023-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0009_alter_entrada_cuerpo_alter_entrada_subtitulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='categorias',
            field=models.ManyToManyField(to='librosApp.categoria'),
        ),
    ]
