# Generated by Django 4.2.4 on 2023-09-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0010_categoria_entrada_categorias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
